[PROFILES]
thinkpad :
    bin-utils
    bin-before
    zsh
    git
    tmux
    nvim
    python
    xdefaults-thinkpad
    xresources
    awesome
    dunst
    xkbdefaults-thinkpad

server :
    zsh
    tmux
    python
    nvim
    git

work :
    awesome
    dunst
    xresources
    python
    zsh
    tmux
    nvim

[awesome]
{PATH}/awesome : ~/.config/awesome

[dunst]
{PATH}/dunst : ~/.config/dunst

[xresources]
{PATH}/xorg/xresources/smyck : ~/.Xresources

[xdefaults-thinkpad]
{PATH}/xorg/xdefaults/thinkpad : ~/.Xdefaults

[xkbdefaults-thinkpad]
{PATH}/xkbdefaults/thinkpad : ~/.xkbdefaults

[bin-utils]
{PATH}/bin/utils : ~/bin/utils

[bin-before]
{PATH}/bin/before : ~/bin/before

[git]
{PATH}/git/gitconfig : ~/.gitconfig
{PATH}/git/gitignore : ~/.gitignore

[zsh]
{PATH}/zsh/zshrc.d : ~/.zshrc.d
{PATH}/zsh/zshenv : ~/.zshenv

[tmux]
{PATH}/tmux/tmux.conf : ~/.tmux.conf

[python]
{PATH}/python : ~/.python
{PATH}/python/virtualenvwrapper/postmkvirtualenv : ~/.virtualenvs/postmkvirtualenv
{PATH}/python/virtualenvwrapper/prermvirtualenv : ~/.virtualenvs/prermvirtualenv

[nvim]
{PATH}/nvim :
    ~/.config/nvim
    ~/.vim
{PATH}/nvim/init.vim : ~/.vimrc
