wallpaper {
    monitor = eDP-1
    path = ~/pictures/wallpaper/stella.png
    fit_mode = cover
}
wallpaper {
    monitor = desc:Eizo Nanao Corporation EV3285 0x022E6D7F
    path = ~/pictures/wallpaper/saya.png
    fit_mode = cover
}
wallpaper {
    monitor =
    path = ~/pictures/wallpaper/saya.png
    fit_mode = cover
}
splash = false
