runtime! vimrc.d/basic/*.vim

if empty(glob("~/.vim/bundle/neobundle.vim/README.md"))
    echo 'neobundle not installed!!(run :DotfilesSubmoduleUpdate)'
    function! DotfilesSubmoduleUpdate()
        cd ~/.dotfiles
        !git submodule init
        !git submodule update
        q
    endfunction
    command DotfilesSubmoduleUpdate :call DotfilesSubmoduleUpdate()
else
    runtime! vimrc.d/plugin/*.vim
endif

